### ISSUE TITLE
cargo build --release Stuck

### ISSUE THREAD

**Issue by hassaan-ali-arista** [stanford-esrg/retina#20]
Running this command takes forever:
```
admin@AN450:~/retina/examples$ cargo build --release --bin basic
    Updating git repository `https://github.com/thegwan/pcap`
    Updating crates.io index
       Fetch [                         ]   0.72%, 1.56KiB/s   
```

**Comment by thegwan** [comment]
This looks like something related to cargo or libgit2: https://github.com/rust-lang/cargo/issues/9177. Perhaps you could try to change the cargo source in ~/.cargo/config to a mirror?

Does a non-release build work?

**Comment by hassaan-ali-arista** [comment]
Yes, it was problem with cargo when fetching the crates.io. I downloaded the crates.io-index repository to my system from: https://github.com/rust-lang/crates.io-index.git and provided the local path to registry in the file ~/.cargo/config as follows:

**[net]
git-fetch-with-cli = true

[source]

[source.mirror]
registry = "file:///home/admin/crates.io-index"

[source.crates-io]
replace-with = "mirror"**

This solved the issue.
