### ISSUE TITLE
3-way Handshake Scenaio

### ISSUE THREAD

**Issue by hassaan-ali-arista** [stanford-esrg/retina#22]
Hi, 

I was trying to filter out the TCP packets involved in a 3-way handshake scenario. Are there any pre-built filters that I can utilize to capture the SYN, SYN-ACK and ACK packets?

**Comment by thegwan** [comment]
Yes, the easiest thing would be to "or" together the TCP flags values for SYN (0x2), SYN-ACK (0x12), and ACK (0x10). The filter parsing doesn't yet support hex values, but you can convert them to decimal like so:

```
#[filter("tcp.flags = 2 or tcp.flags = 18 or tcp.flags = 16")]
```

This will cover both IPv4 and IPv6 packets.
