### ISSUE TITLE
build failed on manjaro system with AMD cpu

### ISSUE THREAD

**Issue by ethan-phu** [stanford-esrg/retina#23]
cpu info:
![image](https://user-images.githubusercontent.com/12579229/208220973-dbbb4166-9cc6-43ef-bffe-64cf6b3a45b3.png)
dpdk version: 22.11.1
env info:
![env info](https://kirashare.oss-cn-beijing.aliyuncs.com/20221217110310.png)
error info:
![erroinfo](https://kirashare.oss-cn-beijing.aliyuncs.com/20221217110201.png)

**Comment by ethan-phu** [comment]
changed the new variable, the error info is change to below:
![image](https://user-images.githubusercontent.com/12579229/208237119-ebb2649e-c6eb-4afd-9fd3-58ef07e7373d.png)

**Comment by thegwan** [comment]
Please use DPDK 21.08, DPDK 22 has some breaking API changes.
