### ISSUE TITLE
URL Filter with Retina

### ISSUE THREAD

**Issue by mmanoj** [stanford-esrg/retina#28]
Hello Team,

I'm planning to use retina as URL filter and block selected URL's. Is there any example like DPDK-l2fw as I need to add retina as transparent bridge. Please advice.

**Comment by thegwan** [comment]
The core Retina framework doesn't natively support forwarding traffic, but the way you could do this is to subscribe to `Frame` with your URL filters and implement the forwarding mechanism (e.g., DPDK tx) inside the callback.
