### ISSUE TITLE
DPDK 21.08在vmware 里面 编译错误

### ISSUE THREAD

**Issue by yidiandianv5** [stanford-esrg/retina#30]
```
root@retina:~# uname -a
Linux retina 6.5.0-26-generic #26~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Mar 12 10:22:43 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

root@retina:~# cat /etc/issue
Ubuntu 22.04.4 LTS \n \l

```
会报：
```
ar: `x' cannot be used on thin archives.
```
使用 `dpdk-stable-21.11.6` 不会

**Comment by tbarbette** [comment]
Hi! Could you provide more context? Which command produces the error you mentioned? This looks like a problem not really related to Retina tough. If you have problems installing DPDK, you might try to check the DPDK mailing list.
