### ISSUE TITLE
Retina tis-parser dependency contribution/ownership

### ISSUE THREAD

**Issue by sippejw** [stanford-esrg/retina#39]
I am planning to make some enhancements to Retina's ability to the TLS ClientHello message. Specifically, I am interested in parsing the [QUIC Transport Parameters](https://www.rfc-editor.org/rfc/rfc9000.html#name-transport-parameter-encodin), a QUIC specific TLS extension that contains a variety of information about how the connection is structured.

Currently, the QUIC parser hands off TLS parsing to the TLS module which depends on a [fork](https://github.com/thegwan/tls-parser) of [`tis-parser`](https://github.com/rusticata/tls-parser) created by @thegwan. I am curious if I should contribute directly to @thegwan's fork or if it would make more sense for this fork to be transferred to stanford-esrg before making any major changes.

**Comment by thearossman** [comment]
@thegwan will work on merging in this fork - thanks for catching!

**Comment by thegwan** [comment]
I've transferred ownership of both tls-parser and dns-parser to stanford-esrg. I'll leave it to one of you to update the dependencies in Cargo, please close the issue when that's done. Thanks for bringing this to my attention!

**Comment by thearossman** [comment]
I'll take care of this today - thanks gerry

**Comment by thearossman** [comment]
Updated in https://github.com/stanford-esrg/retina/pull/44
