### ISSUE TITLE
Tracking Revert of PR #37 

### ISSUE THREAD

**Issue by thearossman** [stanford-esrg/retina#42]
(Since AFAIK Github doesn't let you re-open a merged and reverted PR) 

I just reverted #37 (https://github.com/stanford-esrg/retina/pull/37) because it broke compilation on ARM machines. Details are here: https://github.com/stanford-esrg/retina/pull/41

I worked on this for a bit and couldn't find a relatively quick fix (e.g., replacement library with same API) -- we'd need to find a different library with equivalent functionality. 

@sippejw tagging you so that you're aware this got reverted! As I think you're the primary one using these extra rust-crypto features, there's no rush to fix it. I can also get to it at some point.

**Comment by sippejw** [comment]
PR #55 removes the deprecated dependency and replaces it with `aes-gcm` which is actively maintained.
