### ISSUE TITLE
Cores are not utilized with a pcap file

### ISSUE THREAD

**Issue by HKalbasi** [stanford-esrg/retina#72]
I have a 4GB pcap file with 9M packets, and retina is able to detect its tls and dns traffic in the `basic` example in ~5000 milliseconds (so 6.4 Gbit/s). That's not bad, but far from the advertised 100Gbit/s. I looked at the core usage of the machine, and found that only a single core is 100%, ~5 cores are ~10%, and the rest are zero. So I guessed maybe there is a problem around load balancing.

Here are my questions:
1. How I can configure the number of cores in the offline case? I found the `online.port.cores` for the online usage but nothing equivalent for the offline case.
2. What is the mechanism of load balancing between cores in retina? Where is it defined? In DPDK? How can I configure/change it?

I'm new to retina and DPDK, so sorry for my basic questions and thanks in advance for your time and patience.

**Comment by thearossman** [comment]
Hello! There's no multi-core support for offline mode in Retina. You're right that the RX logic in the Offline runtime is just a single core reading from a pcap file. In general, offline mode is designed for development, functional testing, and perhaps microbenchmarking aspects of the system, not for performance. 

Is there a use-case for Retina that you have that requires high-performance on offline mode? Either way, I can mark this as a feature request for now.

**Comment by HKalbasi** [comment]
Thanks for quick response. I personally have no use for the fast offline case, and was just using it as a benchmark, and I can just use the online mode. So I'm going to close this issue, I can reopen it if there is someone interested in it.

Since I'm new, I have a bunch of these questions/problems. What is your preferred way of communicating them? Are you fine with opening a new issue (and probably closing them soon like this one since they are newbie questions) per each? Or is there a chat group somewhere for these kind of discussions? For instance, I now switched to the online version and I'm seeing some kind of memory leak. The memory usage of mempool slowly goes up and up until it reaches 100% and then retina starts dropping packets. I can open a new issue with more details if you see fit.

**Comment by thearossman** [comment]
I'd say open issues for now, since the "fix" will either be a documentation improvement or an actual fix/feature request. Since Retina is so new, we definitely need support improving the documentation process, so any insights on what isn't clear are exceptionally helpful.

**Comment by thearossman** [comment]
For the mempool exhaustion specifically -- depending on your subscription datatype and network characteristics, it could be known behavior (unfortunately) caused by caching packets for future delivery or reassembly rather than a leak. We're working on developer documentation that will note this, but it should absolutely be documented as an issue and hopefully fixed in the future! (It also could be a memory leak.)
