### ISSUE TITLE
Call filter callbacks in a streaming way

### ISSUE THREAD

**Issue by HKalbasi** [stanford-esrg/retina#74]
In my experiments, I sent dns packets with random four tuple at a 1Gbps rate. I gave retina 12 cores and it had a visible drop percent, which probably makes sense since it is an absurd amount of dns queries. My problem is that it seems retina stores the callback inputs somewhere and only run the callbacks after it becomes finished, and if I choose a long duration it aborts with an out of memory exception (and the strange thing is that I don't see memory consumption increase in htop, and mempool usage is low, I guess dpdk memory is not visible to htop).

I want to run analysis continuously, is it possible to give streaming output from retina?

**Comment by thearossman** [comment]
Unfortunately, no, but this is a core functionality item that we're working on right now! (So helpful to have additional evidence that this is needed for your use-cases.)
